############################################################################
# Copyright 2007-2023 EvoLogics GmbH                                       #
############################################################################
# This file is part of DUNE: Unified Navigation Environment.               #
#                                                                          #
# Commercial Licence Usage                                                 #
# Licencees holding valid commercial DUNE licences may use this file in    #
# accordance with the commercial licence agreement provided with the       #
# Software or, alternatively, in accordance with the terms contained in a  #
# written agreement between you and Faculdade de Engenharia da             #
# Universidade do Porto. For licensing terms, conditions, and further      #
# information contact lsts@fe.up.pt.                                       #
#                                                                          #
# Modified European Union Public Licence - EUPL v.1.1 Usage                #
# Alternatively, this file may be used under the terms of the Modified     #
# EUPL, Version 1.1 only (the "Licence"), appearing in the file LICENCE.md #
# included in the packaging of this file. You may not use this work        #
# except in compliance with the Licence. Unless required by applicable     #
# law or agreed to in writing, software distributed under the Licence is   #
# distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF     #
# ANY KIND, either express or implied. See the Licence for the specific    #
# language governing permissions and limitations at                        #
# https://github.com/LSTS/dune/blob/master/LICENCE.md and                  #
# http://ec.europa.eu/idabc/eupl.html.                                     #
############################################################################
# Author: Victor Voronin                                                   #
############################################################################

[Include common/imc-addresses.ini]

[IMC Addresses]
test-bridge                               = 0x5e5e

[General]
Vehicle                                   = test-bridge

[Transports.UDP]
Enabled                                   = Always
Entity Label                              = UDP
Debug Level                               = Spew
Allow Anonymous Contacts                  = True
Transports                                = CpuUsage,
                                            Current,
                                            Depth,
                                            DevDataText,
                                            Distance,
                                            EntityList,
                                            EntityParameters,
                                            EntityState,
                                            EstimatedState,
                                            FollowRefState,
                                            GpsFix,
                                            Heartbeat,
                                            LogBookControl,
                                            LoggingControl,
                                            PathControlState,
                                            PlanControl,
                                            PlanControlState,
                                            PlanDB,
                                            PlanGeneration,
                                            PlanSpecification,
                                            PowerChannelState,
                                            Pressure,
                                            RelativeHumidity,
                                            RemoteActionsRequest,
                                            Rpm,
                                            ServoPosition,
                                            ServoSpeed,
                                            ServoState,
                                            SetEntityParameters,
                                            SonarData,
                                            StorageUsage,
                                            Temperature,
                                            VehicleState,
                                            Voltage
Filtered Entities                         = CpuUsage:Daemon
Local Port                                = 6062
Print Incoming Messages                   = true
; Print Outgoing Messages                   = false
Rate Limiters                             = CpuUsage:0.2,
                                            Current:2,
                                            DevDataText:1,
                                            EntityState:1,
                                            EstimatedState:5,
                                            GpsFix:2,
                                            RelativeHumidity:0.5,
                                            Rpm:5,
                                            StorageUsage:0.05,
                                            Temperature:0.5,
                                            Voltage:2

[Transports.TCP.Server]
Enabled                                   = Always
Entity Label                              = TCP Server
Debug Level                               = Spew
Trace - Incoming Messages                 = True
Port                                      = 6062
Transports                                = TriggerAction,
                                            EntityList,
                                            EntityParameters,
                                            EntityState

[Transports.Cache]
Enabled                                   = Always
Entity Label                              = Cache

[Transports.TCP.Client]
Enabled                                   = Never
Entity Label                              = TCP to Aux
Server - Address                          = 10.0.0.2
Server - Port                             = 7003
Transports                                = EntityList,
                                            EntityState,
                                            EntityActivationState,
                                            EntityInfo,
                                            EstimatedState,                                         
                                            Heartbeat,
                                            LogBookEntry,
                                            LoggingControl,
                                            PathControl,
                                            Temperature,
                                            VehicleState

[Transports.Announce]
Enabled                                   = Never
Entity Label                              = Announce
Announcement Periodicity                  = 10
Enable Loopback                           = 1
Enable Multicast                          = 1
Enable Broadcast                          = 1
Multicast Address                         = 224.0.75.69
Ports                                     = 30100, 30101, 30102, 30103, 30104
System Type                               = UAV

[Transports.Discovery]
Enabled                                   = Never
Entity Label                              = Discovery
Multicast Address                         = 224.0.75.69
Ports                                     = 30100, 30101, 30102, 30103, 30104
