#!/bin/bash

# GStreamer pipeline receive script.
# Listens for the video stream generated by the send-pipeline.sh script, and displays it.

# Pipeline elements
SOURCE="udpsrc ! application/x-rtp, encoding-name=H264, payload=96, framerate=10/1"
STREAM_DECODER="rtph264depay ! h264parse ! avdec_h264"
STREAM_FILTER="videoconvert"
STREAM_SINK="fpsdisplaysink"

# Pipeline
gst-launch-1.0 -v ${SOURCE} ! queue ! ${STREAM_DECODER} ! ${STREAM_FILTER} ! ${STREAM_SINK}

