[General]
Vehicle                                    = wic-test

[Transports.HTTP]
Enabled                                    = Always
Port                                       = 8080
Threads                                    = 5
Entity Label                               = HTTP Server
Transports                                 = Voltage,
                                             Current,
                                             GpsFix,
                                             EntityState,
                                             CpuUsage,
                                             StorageUsage,
                                             Heartbeat


[Transports.Logging]
Enabled                                    = Always
Entity Label                               = Logger
Flush Interval                             = 5
LSF Compression Method                     = gzip

[Transports.TCP.Client]
Enabled                                   = Never
Entity Label                              = TCP to Main
Server - Address                          = 127.0.0.1
Server - Port                             = 7003
Transports                                = DevDataBinary,
                                            EntityInfo,
                                            EntityList,
                                            EntityParameters,
                                            EntityState,
                                            LogBookEntry,
                                            PlanControl,
                                            PowerChannelState,
                                            Pressure,
                                            RelativeHumidity,
                                            RemoteActions,
                                            Temperature,
                                            Voltage

[Transports.UDP]
Enabled                                    = Always
Entity Label                               = UDP
Transports                                 = SetEntityParameters
Local Port                                 = 6002

[Sensors.WIC]
Enabled                                    = Always
Entity Label                               = WIC
Camera License File Location               = /opt/workswell/wic_sdk/
Camera Range Mode                          = Low 
Camera FFC Mode                            = Manual 
Camera Digital Output Depth                = 16 bit YCbCr
Camera Palette                             = WhiteHot
Camera Brightness                          = 8192
Camera AGC Type                            = PlateauHistogram 
Camera Video Color Mode                    = Color
UDP Destination                            = 192.168.3.153
Use Hardware Encoding                      = false
Record Stream to File                      = false
; Debug Level                                = Spew
