[General]
Vehicle                                    = wic-test

[Transports.HTTP]
Enabled                                    = Always
Port                                       = 8080
Threads                                    = 5
Entity Label                               = HTTP Server
Transports                                 = Voltage,
                                             Current,
                                             GpsFix,
                                             EntityState,
                                             CpuUsage,
                                             StorageUsage,
                                             Heartbeat

[Transports.Logging]
Enabled                                    = Always
Entity Label                               = Logger
Flush Interval                             = 5
LSF Compression Method                     = gzip

[Transports.TCP.Client]
Enabled                                   = Never
Entity Label                              = TCP to Main
Server - Address                          = 127.0.0.1
Server - Port                             = 7003
Transports                                = DevDataBinary,
                                            EntityInfo,
                                            EntityList,
                                            EntityParameters,
                                            EntityState,
                                            LogBookEntry,
                                            PlanControl,
                                            PowerChannelState,
                                            Pressure,
                                            RelativeHumidity,
                                            RemoteActions,
                                            Temperature,
                                            Voltage

[Transports.UDP]
Enabled                                    = Always
Entity Label                               = UDP
Transports                                 = SetEntityParameters
Local Port                                 = 6002

[Sensors.WIC]
Enabled                                   = Always
Entity Label                              = WIC
Color Palette                             = None
Camera - Emissivity                       = 0.95
Camera - Humidity                         = 0.05
Camera - Atmospheric Temperature          = 20.0
Camera - Reflected Temperature            = 20.0
Color Scaling - Method                    = AUTOMATIC - SMOOTHED
Color Scaling - Std Dev Factor            = 2.5
Color Scaling - Manual Min Temperature    = 25.0
Color Scaling - Manual Max Temperature    = 32.0
Invert Colors                             = false
Record Video                              = false
Recordings And Pictures Path              = /home/wic/thermal-camera/
Contrast Correction Method                = NO CONTRAST CORRECTION
Gamma Correction                          = 2.0
CLAHE Tile Size                           = 16
CLAHE Clip Limit                          = 5
Invert Image Horizontally                 = false
Invert Image Vertically                   = false
WIC License File Location                 = /opt/wic/
; Use Hardware Encoding                     = false
UDP Destination                           = 127.0.0.1
Stream Framerate                          = 30
